### ISSUE TITLE
생성되는 모든 Process를 종료하고 싶습니다.

### ISSUE THREAD

**Issue by Jae-kwang** [yangukmo/Loset#4]
저는 아래와 같이 Start Command를 지정해서 사용하고 있습니다.
<img width="511" alt="스크린샷 2020-01-29 오후 3 04 10" src="https://user-images.githubusercontent.com/5828790/73331878-9df15800-42a8-11ea-9312-053f21378b17.png">

그런데 종료 버튼을 누르면 서버가 종료되질 않습니다.

확인해보니 npm 의 process ID를 확인하고 있습니다.
![1580278042959](https://user-images.githubusercontent.com/5828790/73332080-10face80-42a9-11ea-8b76-88bf54642b3d.jpg)

저는 `npm run dev`에서 `node src/index`를 실행시키기 때문에 node의 PID가 종료되어야 하는데 PID가 Loset에 나온거랑 다릅니다.
![1580278459363](https://user-images.githubusercontent.com/5828790/73332423-0ab92200-42aa-11ea-949f-243ba8f6a44d.jpg)

제안, 추가적으로 Port를 옵션으로 받아서 Port있는 경우에는 해당 PID를 종료하면 어떨까요?

**Comment by yangukmo** [comment]
말씀해주신 환경으로 테스트 해보겠습니다 :)

**Comment by yangukmo** [comment]
하위 프로세스를 모두 삭제하도록 수정했습니다.
감사합니다!

**Comment by Jae-kwang** [comment]
https://github.com/yangukmo/Loset/releases/tag/0.1.1
버전으로 받아서 해봤는데 동일한 현상이 재현이 되고 있습니다!
