### ISSUE TITLE
app 추가시 엔터를 누르면 생성이 아닌 선택해선 디렉토리 취소가 됩니다.

### ISSUE THREAD

**Issue by dlqjaen** [yangukmo/Loset#9]
app 추가시 엔터를 누르면 생성이 아닌 선택해선 디렉토리 취소가 됩니다.
추가로 디렉토리 선택에서 취소 버튼을 누르면 입력했던 정보들이 모두 제거가 됩니다.

**Comment by yangukmo** [comment]
`button`태그에 type을 넣어주지 않으면 이상하게 동작하네요.
`form`안의 `input`에서 엔터키를 입력하면,
`form`안의 가장 첫번째 `@click` 이벤트가 실행되어서 발생한 이슈였습니다.

버그 리포팅 감사합니다!
